// VS Code Dark Modern (spec phase1.5 §1 "Default theme" / §2.2): the
// default theme, hand-authored in full since it is both the visual
// reference (`gui/docs/mock/index.html`'s default `:root`) and the
// fallback target every other theme resolves against. Every other built-in
// theme is expanded from a compact palette via `build.ts`; this one is not,
// so its values can match the mock (and real VS Code Dark Modern) exactly.

import type { ThemeColors } from "./tokens";

export const DARK_MODERN_COLORS: ThemeColors = {
  "titleBar.activeBackground": "#181818",
  "titleBar.activeForeground": "#cccccc",
  "titleBar.inactiveBackground": "#181818",
  "menu.background": "#1f1f1f",
  "menu.foreground": "#cccccc",
  "menu.selectionBackground": "#0078d4",
  "menu.selectionForeground": "#ffffff",
  "menu.separatorBackground": "#454545",
  "menu.border": "#454545",

  "sideBar.background": "#181818",
  "sideBar.border": "#2b2b2b",
  "sideBarSectionHeader.foreground": "#cccccc",
  "list.hoverBackground": "#2a2d2e",
  "list.activeSelectionBackground": "#04395e",
  "list.activeSelectionForeground": "#ffffff",
  "list.inactiveSelectionBackground": "#37373d",
  "list.focusOutline": "#0078d4",

  foreground: "#cccccc",
  descriptionForeground: "#9d9d9d",
  "icon.foreground": "#cccccc",
  focusBorder: "#0078d4",
  errorForeground: "#f14c4c",

  "editorGroupHeader.tabsBackground": "#181818",
  "tab.activeBackground": "#1f1f1f",
  "tab.activeForeground": "#ffffff",
  "tab.inactiveBackground": "#181818",
  "tab.inactiveForeground": "#9d9d9d",
  "tab.hoverBackground": "#1f1f1f",
  "tab.activeBorderTop": "#0078d4",
  "tab.border": "#2b2b2b",
  "tab.dragAndDropBorder": "#0078d4",

  "terminal.background": "#1f1f1f",
  "editor.background": "#1f1f1f",
  "terminal.foreground": "#cccccc",
  "terminalCursor.foreground": "#cccccc",
  "terminal.selectionBackground": "#264f78",
  "terminal.ansiBlack": "#000000",
  "terminal.ansiRed": "#cd3131",
  "terminal.ansiGreen": "#0dbc79",
  "terminal.ansiYellow": "#e5e510",
  "terminal.ansiBlue": "#2472c8",
  "terminal.ansiMagenta": "#bc3fbc",
  "terminal.ansiCyan": "#11a8cd",
  "terminal.ansiWhite": "#e5e5e5",
  "terminal.ansiBrightBlack": "#666666",
  "terminal.ansiBrightRed": "#f14c4c",
  "terminal.ansiBrightGreen": "#23d18b",
  "terminal.ansiBrightYellow": "#f5f543",
  "terminal.ansiBrightBlue": "#3b8eea",
  "terminal.ansiBrightMagenta": "#d670d6",
  "terminal.ansiBrightCyan": "#29b8db",
  "terminal.ansiBrightWhite": "#ffffff",

  "statusBar.background": "#181818",
  "statusBar.foreground": "#cccccc",
  "statusBar.border": "#2b2b2b",
  "statusBarItem.hoverBackground": "#2b2b2b",
  "statusBarItem.warningBackground": "#7a5c00",
  "statusBarItem.errorBackground": "#5a1d1d",
  "editorHoverWidget.background": "#202020",
  "editorHoverWidget.border": "#454545",

  "sash.hoverBorder": "#0078d4",
  "progressBar.background": "#0078d4",
  "button.background": "#0078d4",
  "button.foreground": "#ffffff",
  "charts.blue": "#3794ff",
  "charts.orange": "#f0883e",
  "charts.green": "#89d185",

  "herdr.status.working": "#3794ff",
  "herdr.status.blocked": "#f0883e",
  "herdr.status.done": "#89d185",
  "herdr.status.idle": "#9d9d9d",
  "herdr.danger": "#c72e0f",

  "herdr.workspace.1": "#60a5fa",
  "herdr.workspace.2": "#a78bfa",
  "herdr.workspace.3": "#2dd4bf",
  "herdr.workspace.4": "#f472b6",
  "herdr.workspace.5": "#facc15",
  "herdr.workspace.6": "#22d3ee",
  "herdr.workspace.7": "#fb7185",
  "herdr.workspace.8": "#a3e635",
  "herdr.workspace.9": "#818cf8",
  "herdr.workspace.10": "#e879f9",
};
