// Golden surface bytes (spec §9.7): reads the same `.bin`/`.json` pairs that
// `src-tauri/tests/golden_bytes.rs` writes (with `UPDATE_GOLDEN=1`) and
// decodes them with the TypeScript decoder, proving Rust and TS agree on
// the wire format. `decodeSurfaceFrame` is stubbed, so these are expected
// to fail (red) until it is implemented -- but the fixtures themselves are
// real, committed bytes (not stubs), generated by the real Rust encoder.

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { decodeSurfaceFrame } from "../../src/decoder";

const GOLDEN_DIR = join(dirname(fileURLToPath(import.meta.url)), "..", "golden");
const FIXTURES = [
  "full-frame-basic",
  "row-patch-basic",
  // Spec §8a.4: fixtures carrying the optional trailing rust_us u32, proving
  // the decoder reads it when present (the two above prove it defaults to 0
  // when absent).
  "full-frame-with-rust-us",
  "row-patch-with-rust-us",
];

describe("golden surface bytes", () => {
  for (const name of FIXTURES) {
    it(`decodes ${name}.bin to match ${name}.json`, () => {
      const bytes = new Uint8Array(readFileSync(join(GOLDEN_DIR, `${name}.bin`)));
      const expected = JSON.parse(readFileSync(join(GOLDEN_DIR, `${name}.json`), "utf-8"));
      const decoded = decodeSurfaceFrame(bytes);
      expect(decoded).toEqual(expected);
    });
  }
});
